//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignaturasModularizadas.ServicioSQL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSQL.ISQL")]
    public interface ISQL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLCargarDts", ReplyAction="http://tempuri.org/ISQL/SQLCargarDtsResponse")]
        Buscador.ServicioSQL.SQLRespuesta SQLCargarDts(string cadenaSQL, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLCargarDts", ReplyAction="http://tempuri.org/ISQL/SQLCargarDtsResponse")]
        System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLCargarDtsAsync(string cadenaSQL, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLCargarEsquema", ReplyAction="http://tempuri.org/ISQL/SQLCargarEsquemaResponse")]
        Buscador.ServicioSQL.SQLRespuesta SQLCargarEsquema(string cadenaSQL, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLCargarEsquema", ReplyAction="http://tempuri.org/ISQL/SQLCargarEsquemaResponse")]
        System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLCargarEsquemaAsync(string cadenaSQL, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLEjecutar", ReplyAction="http://tempuri.org/ISQL/SQLEjecutarResponse")]
        Buscador.ServicioSQL.SQLRespuesta SQLEjecutar(string cadenaSQL, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLEjecutar", ReplyAction="http://tempuri.org/ISQL/SQLEjecutarResponse")]
        System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLEjecutarAsync(string cadenaSQL, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLEjecutarTrans", ReplyAction="http://tempuri.org/ISQL/SQLEjecutarTransResponse")]
        Buscador.ServicioSQL.SQLRespuesta SQLEjecutarTrans(string cadenaSQL, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLEjecutarTrans", ReplyAction="http://tempuri.org/ISQL/SQLEjecutarTransResponse")]
        System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLEjecutarTransAsync(string cadenaSQL, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLEjecutarEscalar", ReplyAction="http://tempuri.org/ISQL/SQLEjecutarEscalarResponse")]
        Buscador.ServicioSQL.SQLRespuesta SQLEjecutarEscalar(string cadenaSQL, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLEjecutarEscalar", ReplyAction="http://tempuri.org/ISQL/SQLEjecutarEscalarResponse")]
        System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLEjecutarEscalarAsync(string cadenaSQL, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLActualizarImagen", ReplyAction="http://tempuri.org/ISQL/SQLActualizarImagenResponse")]
        Buscador.ServicioSQL.SQLRespuesta SQLActualizarImagen(string cadenaSQL, byte[] lImagen, string CadenaConexion, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISQL/SQLActualizarImagen", ReplyAction="http://tempuri.org/ISQL/SQLActualizarImagenResponse")]
        System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLActualizarImagenAsync(string cadenaSQL, byte[] lImagen, string CadenaConexion, string Clave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISQLChannel : AsignaturasModularizadas.ServicioSQL.ISQL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SQLClient : System.ServiceModel.ClientBase<AsignaturasModularizadas.ServicioSQL.ISQL>, AsignaturasModularizadas.ServicioSQL.ISQL {
        
        public SQLClient() {
        }
        
        public SQLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SQLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SQLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Buscador.ServicioSQL.SQLRespuesta SQLCargarDts(string cadenaSQL, string CadenaConexion, string Clave) {
            return base.Channel.SQLCargarDts(cadenaSQL, CadenaConexion, Clave);
        }
        
        public System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLCargarDtsAsync(string cadenaSQL, string CadenaConexion, string Clave) {
            return base.Channel.SQLCargarDtsAsync(cadenaSQL, CadenaConexion, Clave);
        }
        
        public Buscador.ServicioSQL.SQLRespuesta SQLCargarEsquema(string cadenaSQL, string CadenaConexion, string Clave) {
            return base.Channel.SQLCargarEsquema(cadenaSQL, CadenaConexion, Clave);
        }
        
        public System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLCargarEsquemaAsync(string cadenaSQL, string CadenaConexion, string Clave) {
            return base.Channel.SQLCargarEsquemaAsync(cadenaSQL, CadenaConexion, Clave);
        }
        
        public Buscador.ServicioSQL.SQLRespuesta SQLEjecutar(string cadenaSQL, string CadenaConexion, string Clave) {
            return base.Channel.SQLEjecutar(cadenaSQL, CadenaConexion, Clave);
        }
        
        public System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLEjecutarAsync(string cadenaSQL, string CadenaConexion, string Clave) {
            return base.Channel.SQLEjecutarAsync(cadenaSQL, CadenaConexion, Clave);
        }
        
        public Buscador.ServicioSQL.SQLRespuesta SQLEjecutarTrans(string cadenaSQL, string CadenaConexion, string Clave) {
            return base.Channel.SQLEjecutarTrans(cadenaSQL, CadenaConexion, Clave);
        }
        
        public System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLEjecutarTransAsync(string cadenaSQL, string CadenaConexion, string Clave) {
            return base.Channel.SQLEjecutarTransAsync(cadenaSQL, CadenaConexion, Clave);
        }
        
        public Buscador.ServicioSQL.SQLRespuesta SQLEjecutarEscalar(string cadenaSQL, string CadenaConexion, string Clave) {
            return base.Channel.SQLEjecutarEscalar(cadenaSQL, CadenaConexion, Clave);
        }
        
        public System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLEjecutarEscalarAsync(string cadenaSQL, string CadenaConexion, string Clave) {
            return base.Channel.SQLEjecutarEscalarAsync(cadenaSQL, CadenaConexion, Clave);
        }
        
        public Buscador.ServicioSQL.SQLRespuesta SQLActualizarImagen(string cadenaSQL, byte[] lImagen, string CadenaConexion, string Clave) {
            return base.Channel.SQLActualizarImagen(cadenaSQL, lImagen, CadenaConexion, Clave);
        }
        
        public System.Threading.Tasks.Task<Buscador.ServicioSQL.SQLRespuesta> SQLActualizarImagenAsync(string cadenaSQL, byte[] lImagen, string CadenaConexion, string Clave) {
            return base.Channel.SQLActualizarImagenAsync(cadenaSQL, lImagen, CadenaConexion, Clave);
        }
    }
}
